name: Run Tests
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test
